name: Spellbook
version: '1.1.3'
main: me.japherwocky.spellbook.Spellbook
bootstrapper: me.japherwocky.spellbook.SpellbookBootstrap
api-version: '1.21'
authors: [japherwocky]
description: Custom enchants for paper servers
website: https://japherwocky.me
