name: Spellbook
version: '${project.version}'
main: me.japherwocky.spellbook.Spellbook
bootstrapper: me.japherwocky.spellbook.SpellbookBootstrap
api-version: '1.21.8'
authors: [japherwocky]
description: Custom enchants for paper servers
website: https://japherwocky.me
