name: Release

on:
  release:
    types: [created, edited]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Extract version from tag
      id: version
      run: |
        # Remove 'v' prefix if present (e.g., v1.2.3 -> 1.2.3)
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION=${VERSION#v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Drevision=${{ steps.version.outputs.version }}
    
    - name: Find JAR file
      id: jar
      run: |
        JAR_FILE=$(find target -name "Spellbook-*.jar" -not -name "*-original.jar" | head -1)
        if [ -z "$JAR_FILE" ]; then
          echo "Error: No JAR file found!"
          exit 1
        fi
        echo "jar_path=$JAR_FILE" >> $GITHUB_OUTPUT
        echo "jar_name=$(basename $JAR_FILE)" >> $GITHUB_OUTPUT
        echo "Found JAR: $JAR_FILE"
    
    - name: Upload JAR to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.jar.outputs.jar_path }}
        asset_name: ${{ steps.jar.outputs.jar_name }}
        asset_content_type: application/java-archive
    
    - name: Upload JAR as workflow artifact
      uses: actions/upload-artifact@v4
      with:
        name: spellbook-release-${{ steps.version.outputs.version }}
        path: ${{ steps.jar.outputs.jar_path }}
        if-no-files-found: error
